"""update Item model

Revision ID: 199f217addb3
Revises: 36086d9807e0
Create Date: 2021-11-12 18:35:28.457257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199f217addb3'
down_revision = '36086d9807e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
