"""update Item model

Revision ID: 36086d9807e0
Revises: c945491be240
Create Date: 2021-11-12 18:22:15.244003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36086d9807e0'
down_revision = 'c945491be240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
