"""add hash to item

Revision ID: 68be5904d3fd
Revises: c2f3b5438941
Create Date: 2021-11-15 21:08:43.297338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68be5904d3fd'
down_revision = 'c2f3b5438941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'item', ['hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'hash')
    # ### end Alembic commands ###
