"""update Item model

Revision ID: 818859c4f96b
Revises: 199f217addb3
Create Date: 2021-11-12 18:38:13.980853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818859c4f96b'
down_revision = '199f217addb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
