"""add some fields to Item

Revision ID: aeaf3ef6dab6
Revises: 22c943fb7880
Create Date: 2021-11-05 21:27:34.212481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaf3ef6dab6'
down_revision = '22c943fb7880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('item', sa.Column('type', sa.String(), nullable=True))
    op.add_column('item', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('item', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('qaod', sa.DATE(), nullable=True))
    op.drop_index('ix_item_title', table_name='item')
    op.create_index(op.f('ix_item_sku'), 'item', ['sku'], unique=False)
    op.create_index(op.f('ix_item_type'), 'item', ['type'], unique=False)
    op.drop_column('item', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_type'), table_name='item')
    op.drop_index(op.f('ix_item_sku'), table_name='item')
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.drop_column('item', 'qaod')
    op.drop_column('item', 'quantity')
    op.drop_column('item', 'price')
    op.drop_column('item', 'type')
    op.drop_column('item', 'sku')
    # ### end Alembic commands ###
