"""update asset

Revision ID: c2f3b5438941
Revises: 7ee2448c3e8b
Create Date: 2021-11-15 05:17:15.093297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f3b5438941'
down_revision = '7ee2448c3e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('background', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'background')
    # ### end Alembic commands ###
