"""add attrs for qrcode to item

Revision ID: c945491be240
Revises: 1a9ad6d59ddf
Create Date: 2021-11-12 18:18:13.337482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c945491be240'
down_revision = '1a9ad6d59ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('item', sa.Column('background', sa.String(), nullable=True))
    op.add_column('item', sa.Column('headerText', sa.String(), nullable=True))
    op.add_column('item', sa.Column('headerColor', sa.String(), nullable=True))
    op.add_column('item', sa.Column('subHeaderText', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'subHeaderText')
    op.drop_column('item', 'headerColor')
    op.drop_column('item', 'headerText')
    op.drop_column('item', 'background')
    op.drop_column('item', 'logo')
    # ### end Alembic commands ###
